version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: microservice-java:latest
    container_name: my_spring_app
    environment:
      DB_URL: postgres
      FRONTEND_URL: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:

# run with: docker-compose up -d
