spring:
  application:
    name: microservice-demo-java
  r2dbc:
    url: "r2dbc:postgresql://localhost/postgres"
    username: "root"
    password: "rootpassword"
  liquibase:
    url: "jdbc:postgresql://localhost/postgres"
    password: "rootpassword"
    user: "root"
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
