spring:
  application:
    name: microservice-demo-java
  r2dbc:
    url: "r2dbc:postgresql://localhost/postgres"
    username: "root"
    password: "rootpassword"
  data:
    mongodb:
      uri: "mongodb://root:example@localhost:27017/test?authSource=admin"
  liquibase:
    url: "jdbc:postgresql://localhost/postgres"
    user: "root"
    password: "rootpassword"
    change-log: "classpath:/db/changelog.yaml"
