spring:
  application:
    name: microservice-demo-java
  r2dbc:
    url: "r2dbc:postgresql://localhost/postgres"
    username: "root"
    password: "rootpassword"
  mongodb:
    host: "localhost"
    port: 27017
    database: "test"
    username: "root"
    password: "example"
  liquibase:
    url: "jdbc:postgresql://localhost/postgres"
    user: "root"
    password: "rootpassword"
    change-log: "classpath:/db/changelog.yaml"
